### PR TITLE
Eb 1127

### PR DESCRIPTION
**Pull request by tom6931**
Modified quickstarts to use pip3 install.  Added comment about possibility of not using sudo.

### CODE REVIEW

**Comment by christiam** [comment]
@tom6931 - would it be possible to keep the instructions to get ElasticBLAST from GCP via curl? I think this gives us more avenues to get ElasticBLAST.

**Comment by boratyng** [comment]
I agree with @christiam about giving people multiple ways to install elastic-blast. They can choose one with which they feel comfortable.

**Comment by tom6931** [comment]
I'm not a big fan of the curl approach.  I could see leaving it somewhere, but I'd prefer not to make the quickstart more complicated.

**Comment by boratyng** [comment]
Maybe a separate "How to install" page and then a single installation method in Quickstart.

**Review by boratyng — APPROVED** [review]

**Comment by tom6931** [comment]
Change for pypi but preserve curl instructions in tutorials.

**Pull request merged**
