### PR TITLE
Release 0.2.6

### PR DESCRIPTION
**Pull request by boratyng**
* Updated version to 0.2.6
* Updated docs for GCP project and documented GKE version

### CODE REVIEW

**Comment by boratyng** [comment]
We can now also remove `cloud-provider` config from quick starts. Elastic-blast will then run in `us-east-1` for AWS and `us-east4-b` for GCP. The default GCP project set in `gcloud` config will be used. I tested that it works both in AWS and GCP.

**Comment by boratyng** [comment]
Maybe this was too many details. How about just saying:
Default: Default `gcloud` project.

There is a description on how to check the default project (just above the code block) and I can also add how to set it.

In my opinion "in environment" makes this description confusing, because environment typically means shell environment. gcloud config is defined in a file and can be overwritten by environment variables.  `CLOUDSDK_CORE_PROJECT` is used by gcloud so "default gcloud project" means gcloud config that can be overwritten by the environment variable.

**Comment by tom6931** [comment]
Yes.  Simpler is better.  I'm fine with what's up there.  We have people waiting for this, so I'd like to get the release out.

**Comment by boratyng** [comment]
@tom6931, I updated the description of default GCP project.

**Comment by tom6931** [comment]
Looks good.

**Review by christiam — APPROVED** [review]

**Pull request merged**
