### PR TITLE
Document gcp-setup-elastic-blast-janitor.sh script to set up GCP janitor

### PR DESCRIPTION
**Pull request by christiam**
- Documentation updates for newly added script gcp-setup-elastic-blast-janitor.sh

### CODE REVIEW

**Review by tom6931 — COMMENTED** [review]
I think we want to reiterate that a user needs to manually call delete if they cannot enable auto-shutdown.  See the last two sentences of the paragraph below.

If this operation fails, you may need to ask your GCP account administrator to
run the command on your behalf. If this is not possible, setting the
``ELB_DISABLE_AUTO_SHUTDOWN`` and ``ELB_DISABLE_JOB_SUBMISSION_ON_THE_CLOUD``
environment variables to any value will disable
the auto-shutdown feature and remove the requirement for these additional
permissions.   You will then need to manually invoke delete after completion of your search.  Otherwise, you will incur charges for those remaining resources.

**Comment by christiam** [comment]
@tom6931 , the following text is in bold at the top of this page: 
Screen Shot 2022-03-09 at 1 56 40 PM

Are you suggesting to highlight (i.e.: put in bold, or underline) the text 
> You will then need to manually invoke delete after completion of your search. Otherwise, you will incur charges for those remaining resources.

**Comment by tom6931** [comment]
I'm worried about the phrase "and remove the requirement for these additional
permissions. "  I could read this as meaning don't worry about this.  How about removing that part?  People will do stupid stuff, incur charges, and blame us.

**Comment by christiam** [comment]
> I'm worried about the phrase "and remove the requirement for these additional permissions. " I could read this as meaning don't worry about this. How about removing that part?

This is done in revision 97f5d89

**Comment by christiam** [comment]
I restored the information on environment variables to disable this feature in 18afd0e

**Review by tom6931 — APPROVED** [review]

**Pull request merged**
