### PR TITLE
Remove needless configuration options for enabling auto-scaling in GCP

### PR DESCRIPTION
**Pull request by christiam**
Per changes from EB-857

### CODE REVIEW

**Comment by tom6931** [comment]
Was there a change in the latest release so this no longer applies or was it just outdated?

**Comment by christiam** [comment]
> Was there a change in the latest release so this no longer applies or was it just outdated?

@tom6931 ,
No, the latest release (0.1.3) hasn't been updated. This pull request is queueing up changes for the next release (0.1.4).

**Comment by tom6931** [comment]
OK with me.

**Review by tom6931 — APPROVED** [review]
OK with me.

**Pull request merged**
