### PR TITLE
Add known issue for GCP

### PR DESCRIPTION
**Pull request by christiam**
This is to inform GCP users of the required change for ElasticBLAST 1.0.0 to work. The formatted output looks as follows:

Screen Shot 2023-04-26 at 4 56 58 PM

### CODE REVIEW

**Comment by tom6931** [comment]
This fine, but I I also needed to downgrade kubeclt to 1.18, which we say on https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/requirements.html is not supported.

**Comment by boratyng** [comment]
We should probably test newer kubectl versions and update requirements.

**Review by boratyng — APPROVED** [review]

**Comment by christiam** [comment]
@tom6931 , @boratyng - I tested multiple versions of kubectl with this configuration parameter and the all work well.

**Comment by boratyng** [comment]
Looks good to me.

**Comment by christiam** [comment]
> This fine, but I I also needed to downgrade kubeclt to 1.18, which we say on https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/requirements.html is not supported.

@tom6931  - in reviewing the requirements I can see how the language is confusing. Here is a pull request that hopefully addresses that: #164

**Review by tom6931 — COMMENTED** [review]
This should either be repeated in the GCP requirements or there should be a pointer to this for 1.0.0 (or lower?) users.

**Comment by christiam** [comment]
> This should either be repeated in the GCP requirements or there should be a pointer to this for 1.0.0 (or lower?) users.

ElasticBLAST prior to 1.0.0 does not work anymore: per https://blast.ncbi.nlm.nih.gov/doc/elastic-blast/gcp-issues.html#upgrade-required-for-gcp-elasticblast-users

I added a link to the GCP known issue for ElasticBLAST version 1.0.0 in bdf77c3 .

**Comment by christiam** [comment]
Here's a preview of the change in the banner:

Screen Shot 2023-04-28 at 10 07 11 AM

**Review by tom6931 — APPROVED** [review]

**Review by boratyng — APPROVED** [review]

**Pull request merged**
